package main

import (
	"log"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/fsnotify/fsnotify"
	"github.com/wailsapp/wails/v2/pkg/runtime"
)

var (
	watcher    *fsnotify.Watcher
	watcherMu  sync.Mutex
	processing sync.Map // track files being processed
	watcherDone chan struct{} // track watcher goroutine exit
)

// updateWatcher restarts the fsnotify watcher for the given directory
func (a *App) updateWatcher(folder string) error {
	watcherMu.Lock()
	defer watcherMu.Unlock()

	// Stop existing watcher
	if watcher != nil {
		watcher.Close()
		if watcherDone != nil {
			<-watcherDone // wait for goroutine to exit
		}
		watcher = nil
	}

	if folder == "" {
		return nil
	}

	w, err := fsnotify.NewWatcher()
	if err != nil {
		log.Println("Error creating watcher:", err)
		return err
	}
	watcher = w

	err = watcher.Add(folder)
	if err != nil {
		log.Println("Error adding watcher for folder:", folder, err)
		watcher.Close()
		watcher = nil
		return err
	}

	wDone := make(chan struct{})
	watcherDone = wDone

	go func() {
		defer close(wDone)
		for {
			select {
			case event, ok := <-w.Events:
				if !ok {
					return
				}
				if event.Has(fsnotify.Create) || event.Has(fsnotify.Write) {
					// Check if file is image and not already processed
					ext := strings.ToLower(filepath.Ext(event.Name))
					if ext == ".jpg" || ext == ".jpeg" || ext == ".png" {
						// Skip files generated by ExifFrame
						if strings.Contains(event.Name, "_ExifFrame") {
							continue
						}

						// Basic debounce tracking
						if _, loaded := processing.LoadOrStore(event.Name, true); loaded {
							continue
						}

						go func(filePath string) {
							defer processing.Delete(filePath)

							// Wait for file size to stabilize (up to 5 seconds)
							var lastSize int64 = -1
							for i := 0; i < 10; i++ {
								info, err := os.Stat(filePath)
								if err != nil {
									time.Sleep(500 * time.Millisecond)
									continue
								}
								if info.Size() == lastSize && lastSize > 0 {
									break
								}
								lastSize = info.Size()
								time.Sleep(500 * time.Millisecond)
							}

							// Process the file
							log.Println("Processing new file:", filePath)
							a.processBackgroundFile(filePath)
						}(event.Name)
					}
				}
			case err, ok := <-w.Errors:
				if !ok {
					return
				}
				log.Println("Watcher error:", err)
			}
		}
	}()

	return nil
}

// processBackgroundFile extracts EXIF and sends it to the frontend quietly
func (a *App) processBackgroundFile(filePath string) {
	if a.ctx == nil {
		return
	}

	// Make sure we have the settings for export
	settingsMu.RLock()
	exportFolder := currentSettings.ExportFolder
	settingsMu.RUnlock()
	if exportFolder == "" {
		log.Println("No export folder configured")
		return
	}

	result := a.processImageFile(filePath)
	if result.Error != "" {
		log.Println("Background process error:", result.Error)
		return
	}

	// Emit event to frontend with file details
	runtime.EventsEmit(a.ctx, "process_file", map[string]interface{}{
		"result": result,
		"export": exportFolder,
	})
}
