export interface ExifData {
    camera: string;
    lens: string;
    focalLength: string;
    aperture: string;
    shutterSpeed: string;
    iso: string;
    film: string;
    developer: string;
    dilution: string;
    temperature: string;
    time: string;
}

export interface MetadataVisibility {
    camera: boolean;
    lens: boolean;
    focalLength: boolean;
    aperture: boolean;
    shutterSpeed: boolean;
    iso: boolean;
    film: boolean;
    developer: boolean;
    dilution: boolean;
    temperature: boolean;
    time: boolean;
}

export const VISIBILITY_KEYS = [
    'camera', 'lens', 'focalLength', 'aperture', 'shutterSpeed', 'iso',
    'film', 'developer', 'dilution', 'temperature', 'time',
] as const;

export const settingsKey = (k: typeof VISIBILITY_KEYS[number]) =>
    k === 'iso' ? 'visibilityISO' : `visibility${k.charAt(0).toUpperCase()}${k.slice(1)}`;

export function toVisibility(s: Record<string, unknown>): MetadataVisibility {
    const result: Partial<MetadataVisibility> = {};
    VISIBILITY_KEYS.forEach(k => {
        const val = s[settingsKey(k)];
        result[k] = typeof val === 'boolean' ? val : true;
    });
    return result as MetadataVisibility;
}

export function applyVisibility(s: Record<string, unknown>, v: MetadataVisibility): void {
    VISIBILITY_KEYS.forEach(k => { s[settingsKey(k)] = v[k]; });
}

export interface ImportedImage {
    /** The original local file path of the image. */
    filePath: string;
    
    /** A local HTTP URL generated by the backend representing the image data. Used as the src for HTMLImageElements. */
    imageURL: string;
    
    /** The MIME type of the original source image. */
    sourceMimeType: 'image/jpeg' | 'image/png';
    
    exif: ExifData;
    frameColor?: string;
    textColor?: string;
    orientation?: "landscape" | "portrait";
    aspectRatioPreset?: string;
    customRatioW?: number;
    customRatioH?: number;
    alignment?: "top" | "center";
    showPipeSeparator?: boolean;
    fontFamily?: string;
    originalBPP?: number;
    
    /** The decoded image object loaded into memory. Lazily initialized on demand. */
    imageObj: HTMLImageElement | null;
    
    /** Flag indicating if the image failed to load, preventing infinite retry loops. */
    loadError?: boolean;
}

export interface ExifResult {
    error?: string;
    cancelled?: boolean;
    imageURL?: string;
    filePath?: string;
    mimeType?: string;
    camera?: string;
    lens?: string;
    focalLength?: string;
    aperture?: string;
    shutterSpeed?: string;
    iso?: string;
    originalBPP?: number;
}

export const DEFAULT_FONT_FAMILY = "Arial";

export const CSS_GENERIC_FONTS = [
    'serif', 'sans-serif', 'monospace', 'cursive', 'fantasy', 
    'system-ui', 'ui-serif', 'ui-sans-serif', 'ui-monospace', 
    'ui-rounded', 'math', 'emoji', 'fangsong'
];
