// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetSettings():Promise<main.Settings>;

export function OpenImage():Promise<main.ExifResult>;

export function SaveAutoImage(arg1:boolean,arg2:string):Promise<main.SaveResult>;

export function SaveImage(arg1:boolean,arg2:string):Promise<main.SaveResult>;

export function SaveSettings(arg1:main.Settings):Promise<string>;

export function SelectExportFolder():Promise<string>;

export function SelectWatchFolder():Promise<string>;
