// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function OpenImage() {
  return window['go']['main']['App']['OpenImage']();
}

export function SaveAutoImage(arg1, arg2) {
  return window['go']['main']['App']['SaveAutoImage'](arg1, arg2);
}

export function SaveImage(arg1, arg2) {
  return window['go']['main']['App']['SaveImage'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectExportFolder() {
  return window['go']['main']['App']['SelectExportFolder']();
}

export function SelectWatchFolder() {
  return window['go']['main']['App']['SelectWatchFolder']();
}
