// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenImage() {
  return window['go']['main']['App']['OpenImage']();
}

export function SaveImage(arg1) {
  return window['go']['main']['App']['SaveImage'](arg1);
}
